name: Docker Build back-end

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion à DockerHub
      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construction et publication de l'image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest